name: Auto Merge PR

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: ""   # Optionally specify labels that allow merging (empty means no label filter)