name: Auto Merge PR

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Auto Merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "🔁 Attempting to merge PR #$PR_NUMBER"
          gh pr merge $PR_NUMBER --squash --admin --delete-branch=false
