name: Auto Merge PR

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Auto Merge PR
        env:
          GH_TOKEN: ${{ steps['app-token'].outputs.token }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "🔁 Attempting to merge PR #$PR_NUMBER"
          gh pr merge $PR_NUMBER --squash --admin --delete-branch=false
