name: 'check-pr-branch'

on:
  pull_request:
    branches:
      - main
      - stage

jobs:
  check_pr_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Branch
        if: >
          (github.base_ref == 'main' && github.head_ref != 'stage') || 
          (github.base_ref == 'stage' && github.head_ref != 'develop')
        uses: actions/github-script@v7
        with:
          script: core.setFailed('Invalid base branch for PR. You can only merge to main from stage and to stage from develop.')